// Package router provides Laravel-style declarative routing that is
// independent of any HTTP framework. You declare routes once; each
// adapter (Gin/Fiber/Echo/Chi/net/http) mounts them with a one-liner.
//
// Example:
//
//	r := router.New()
//	r.Get("/health", healthHandler)
//	r.Resource("posts", postsCtrl)
//	r.Group("/api/v1", func(g *router.Router) {
//	    g.Use(authMiddleware)
//	    g.Resource("users", usersCtrl)
//	})
//
// Then mount onto your framework:
//
//	r.MountStd(http.NewServeMux())            // net/http
//	r.Apply(func(method, path string, h http.HandlerFunc) {
//	    ginEngine.Handle(method, path, gin.WrapF(h))
//	})
package router

import (
	"net/http"
	"strings"
)

// Handler is the framework-agnostic handler signature. It is identical to
// http.HandlerFunc — controllers generated by `lago make:controller`
// already conform.
type Handler = http.HandlerFunc

// Middleware wraps a Handler. Middleware compose left-to-right.
type Middleware func(Handler) Handler

// ResourceController is the contract for `r.Resource("posts", ctrl)`.
// Implementations may leave any method as a no-op; the router only wires
// the methods present.
type ResourceController interface {
	Index(w http.ResponseWriter, r *http.Request)
	Show(w http.ResponseWriter, r *http.Request)
	Store(w http.ResponseWriter, r *http.Request)
	Update(w http.ResponseWriter, r *http.Request)
	Destroy(w http.ResponseWriter, r *http.Request)
}

// Route is one row in the route table. It is exposed so adapters can
// introspect (e.g. for printing the route list).
type Route struct {
	Method  string
	Path    string
	Handler Handler
	Name    string
}

// Router collects routes, groups, and middleware in declaration order.
// It is not goroutine-safe — declare routes from a single goroutine at
// startup, then mount onto your server.
type Router struct {
	prefix      string
	middlewares []Middleware
	routes      []Route
	parent      *Router
}

// New constructs an empty top-level router.
func New() *Router { return &Router{} }

// Use installs middleware that wraps every subsequent handler registered
// on this router (and its children via Group).
func (r *Router) Use(mw ...Middleware) {
	r.middlewares = append(r.middlewares, mw...)
}

// Group runs the callback against a child router with the given path
// prefix. Middleware on the parent applies to the child; new Use() calls
// inside fn add to the child only.
func (r *Router) Group(prefix string, fn func(g *Router)) {
	child := &Router{
		prefix:      r.joinPath(prefix),
		middlewares: append([]Middleware(nil), r.middlewares...),
		parent:      r,
	}
	fn(child)
	r.routes = append(r.routes, child.routes...)
}

// HTTP verb shortcuts. Each registers a route with the router's prefix
// and applies its middleware chain to the handler.
func (r *Router) Get(path string, h Handler)     { r.add(http.MethodGet, path, h) }
func (r *Router) Post(path string, h Handler)    { r.add(http.MethodPost, path, h) }
func (r *Router) Put(path string, h Handler)     { r.add(http.MethodPut, path, h) }
func (r *Router) Patch(path string, h Handler)   { r.add(http.MethodPatch, path, h) }
func (r *Router) Delete(path string, h Handler)  { r.add(http.MethodDelete, path, h) }
func (r *Router) Options(path string, h Handler) { r.add(http.MethodOptions, path, h) }
func (r *Router) Head(path string, h Handler)    { r.add(http.MethodHead, path, h) }

// Any registers the handler for every standard HTTP verb.
func (r *Router) Any(path string, h Handler) {
	for _, m := range []string{
		http.MethodGet, http.MethodPost, http.MethodPut,
		http.MethodPatch, http.MethodDelete, http.MethodHead, http.MethodOptions,
	} {
		r.add(m, path, h)
	}
}

// Resource registers the five canonical RESTful routes for a controller:
//
//	GET    /posts            → ctrl.Index
//	GET    /posts/{id}       → ctrl.Show
//	POST   /posts            → ctrl.Store
//	PUT    /posts/{id}       → ctrl.Update
//	PATCH  /posts/{id}       → ctrl.Update
//	DELETE /posts/{id}       → ctrl.Destroy
//
// The `name` argument is the plural resource name (`posts`, `users`, …).
func (r *Router) Resource(name string, ctrl ResourceController) {
	base := "/" + strings.Trim(name, "/")
	r.Get(base, ctrl.Index)
	r.Get(base+"/{id}", ctrl.Show)
	r.Post(base, ctrl.Store)
	r.Put(base+"/{id}", ctrl.Update)
	r.Patch(base+"/{id}", ctrl.Update)
	r.Delete(base+"/{id}", ctrl.Destroy)
}

// APIResource is identical to Resource — kept as a convenience alias to
// match the user-facing Laravel naming convention.
func (r *Router) APIResource(name string, ctrl ResourceController) { r.Resource(name, ctrl) }

func (r *Router) add(method, path string, h Handler) {
	full := r.joinPath(path)
	// Apply middleware in declaration order: the FIRST registered
	// middleware is the outermost wrapper (it sees the request first).
	wrapped := h
	for i := len(r.middlewares) - 1; i >= 0; i-- {
		wrapped = r.middlewares[i](wrapped)
	}
	r.routes = append(r.routes, Route{Method: method, Path: full, Handler: wrapped})
}

func (r *Router) joinPath(p string) string {
	if p == "" || p == "/" {
		// A root path on a prefix-less router would otherwise yield "",
		// which net/http's ServeMux rejects ("host/path missing /") and
		// panics on registration. Normalise to "/" so Get("/") on the
		// top-level router mounts cleanly.
		if r.prefix == "" {
			return "/"
		}
		return r.prefix
	}
	if r.prefix == "" {
		return "/" + strings.TrimLeft(p, "/")
	}
	return strings.TrimRight(r.prefix, "/") + "/" + strings.TrimLeft(p, "/")
}

// Routes returns a snapshot of every registered route in declaration order.
// Useful for printing the route table at startup.
func (r *Router) Routes() []Route {
	out := make([]Route, len(r.routes))
	copy(out, r.routes)
	return out
}

// Apply invokes register for every route. Frameworks register routes via
// a one-line callback:
//
//	r.Apply(func(method, path string, h http.HandlerFunc) {
//	    ginEngine.Handle(method, path, gin.WrapF(h))
//	})
func (r *Router) Apply(register func(method, path string, h Handler)) {
	for _, rt := range r.routes {
		register(rt.Method, rt.Path, rt.Handler)
	}
}

// MountStd registers every route on a net/http ServeMux using the
// "METHOD /path" syntax introduced in Go 1.22.
func (r *Router) MountStd(mux *http.ServeMux) {
	r.Apply(func(method, path string, h Handler) {
		mux.HandleFunc(method+" "+path, h)
	})
}

// Common middleware ------------------------------------------------------

// Chain composes middleware as a single Middleware. Useful when you want
// to apply a stable bundle (logging + recovery + auth) in one call.
func Chain(mw ...Middleware) Middleware {
	return func(next Handler) Handler {
		for i := len(mw) - 1; i >= 0; i-- {
			next = mw[i](next)
		}
		return next
	}
}
