package cmd

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// ScaffoldOptions captures every interactive choice `lago new` made.
// The deploy/code stubs are conditional on these fields so the
// generated project only carries services it actually uses.
type ScaffoldOptions struct {
	Name      string // app name, used in env / compose service name
	Module    string // Go module path
	Framework string // "web" | "gin"
	Database  string // "postgres" | "mysql" | "sqlite" | "none"
	Cache     string // "redis" | "none"
	Storage   string // "minio" | "none"
}

// ----------------------------------------------------------------------
// Dockerfile (multi-stage, distroless, non-root)
// ----------------------------------------------------------------------

const dockerfileTmpl = `# syntax=docker/dockerfile:1.7
# Multi-stage build. Final image runs as a non-root user on a
# distroless base — no shell, no package manager, smaller attack
# surface than alpine.

# --- build stage --------------------------------------------------------
FROM golang:1.25-alpine AS build
WORKDIR /src

# Pre-cache modules.
COPY go.mod go.sum* ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

# Build a statically-linked binary.
COPY . .
ARG VERSION=dev
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux \
    go build -trimpath -ldflags "-s -w -X main.version=${VERSION}" \
        -o /out/app .

# --- runtime stage ------------------------------------------------------
FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /app

# Copy the binary and the migrations / config directories the runtime
# may need at boot. Add other dirs (templates/, locales/, …) as needed.
COPY --from=build /out/app /app/app

USER nonroot:nonroot
EXPOSE 8080

ENV APP_ENV=production \
    APP_ADDR=:8080

ENTRYPOINT ["/app/app"]
`

// ----------------------------------------------------------------------
// docker-compose.yml
// ----------------------------------------------------------------------

// composeTmpl is a Go text/template so we can selectively include
// services. `.Database`, `.Cache`, `.Storage` drive the conditional
// blocks.
const composeTmpl = `# Generated by lago new. Edit freely — the next ` + "`lago new`" + ` does
# not overwrite this file.

services:
  app:
    build:
      context: .
      args:
        VERSION: dev
    image: {{.Name}}:dev
    container_name: {{.Name}}-app
    ports:
      - "8080:8080"
    environment:
      APP_ENV: local
      APP_ADDR: ":8080"
{{- if eq .Database "postgres"}}
      DB_CONNECTION: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: app
      DB_PASSWORD: secret
      DB_DATABASE: {{.Name}}
{{- end}}
{{- if eq .Database "mysql"}}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: app
      DB_PASSWORD: secret
      DB_DATABASE: {{.Name}}
{{- end}}
{{- if eq .Database "sqlite"}}
      DB_CONNECTION: sqlite
      DB_DATABASE: /data/app.db
{{- end}}
{{- if eq .Cache "redis"}}
      REDIS_ADDR: redis:6379
{{- end}}
{{- if eq .Storage "minio"}}
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET: {{.Name}}
      S3_USE_SSL: "false"
{{- end}}
    depends_on:
{{- if eq .Database "postgres"}}
      postgres:
        condition: service_healthy
{{- end}}
{{- if eq .Database "mysql"}}
      mysql:
        condition: service_healthy
{{- end}}
{{- if eq .Cache "redis"}}
      redis:
        condition: service_healthy
{{- end}}
{{- if eq .Storage "minio"}}
      minio:
        condition: service_healthy
{{- end}}
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks: [{{.Name}}]
{{- if eq .Database "sqlite"}}
    volumes:
      - sqlite_data:/data
{{- end}}

{{if eq .Database "postgres"}}
  postgres:
    image: postgres:16-alpine
    container_name: {{.Name}}-postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: {{.Name}}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d {{.Name}}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks: [{{.Name}}]
{{end}}
{{if eq .Database "mysql"}}
  mysql:
    image: mysql:8.4
    container_name: {{.Name}}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: {{.Name}}
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pappsecret"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [{{.Name}}]
{{end}}
{{if eq .Cache "redis"}}
  redis:
    image: redis:7-alpine
    container_name: {{.Name}}-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - redis_data:/data
    networks: [{{.Name}}]
{{end}}
{{if eq .Storage "minio"}}
  minio:
    image: minio/minio:latest
    container_name: {{.Name}}-minio
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - minio_data:/data
    networks: [{{.Name}}]
{{end}}

volumes:
{{- if eq .Database "postgres"}}
  pg_data:
{{- end}}
{{- if eq .Database "mysql"}}
  mysql_data:
{{- end}}
{{- if eq .Database "sqlite"}}
  sqlite_data:
{{- end}}
{{- if eq .Cache "redis"}}
  redis_data:
{{- end}}
{{- if eq .Storage "minio"}}
  minio_data:
{{- end}}

networks:
  {{.Name}}:
    driver: bridge
`

// ----------------------------------------------------------------------
// Kubernetes manifests
// ----------------------------------------------------------------------

const k8sDeploymentTmpl = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    app: {{.Name}}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{.Name}}
  template:
    metadata:
      labels:
        app: {{.Name}}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
      containers:
        - name: app
          image: {{.Name}}:dev   # set via your CI / Helm overlay
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{.Name}}-config
            - secretRef:
                name: {{.Name}}-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
`

const k8sServiceTmpl = `apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    app: {{.Name}}
spec:
  type: ClusterIP
  selector:
    app: {{.Name}}
  ports:
    - name: http
      port: 80
      targetPort: http
`

const k8sConfigMapTmpl = `apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Name}}-config
data:
  APP_ENV: "production"
  APP_ADDR: ":8080"
{{- if eq .Database "postgres"}}
  DB_CONNECTION: "postgres"
  DB_PORT: "5432"
  DB_DATABASE: "{{.Name}}"
{{- end}}
{{- if eq .Database "mysql"}}
  DB_CONNECTION: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "{{.Name}}"
{{- end}}
{{- if eq .Cache "redis"}}
  REDIS_ADDR: "redis:6379"
{{- end}}
{{- if eq .Storage "minio"}}
  S3_BUCKET: "{{.Name}}"
  S3_USE_SSL: "true"
{{- end}}
`

const k8sSecretTmpl = `# Replace placeholder values before applying — for real deployments
# generate via External Secrets Operator, Sealed Secrets, or SOPS.
apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}-secrets
type: Opaque
stringData:
{{- if or (eq .Database "postgres") (eq .Database "mysql")}}
  DB_HOST: "REPLACE_ME"
  DB_USERNAME: "REPLACE_ME"
  DB_PASSWORD: "REPLACE_ME"
{{- end}}
{{- if eq .Storage "minio"}}
  S3_ENDPOINT: "REPLACE_ME"
  S3_ACCESS_KEY: "REPLACE_ME"
  S3_SECRET_KEY: "REPLACE_ME"
{{- end}}
  APP_KEY: "REPLACE_ME_RUN_lago_key_generate"
  JWT_SECRET: "REPLACE_ME_RUN_lago_key_generate"
`

const k8sKustomizationTmpl = `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
`

// ----------------------------------------------------------------------
// .dockerignore
// ----------------------------------------------------------------------

const dockerIgnore = `.git
.gitignore
.dockerignore
.env
.env.*
*.md
tmp/
bin/
*.test
*.out
coverage.*
docker-compose.yml
Dockerfile
k8s/
node_modules/
`

// ----------------------------------------------------------------------
// renderTemplate is a tiny wrapper around text/template that returns
// the rendered string. It panics on a bad template (these are author-
// time strings, so a panic surfaces the bug immediately during ` + "`go test`" + `).
// ----------------------------------------------------------------------

func renderTemplate(name, body string, opts ScaffoldOptions) (string, error) {
	tmpl, err := template.New(name).Parse(body)
	if err != nil {
		return "", fmt.Errorf("scaffold: parse %s: %w", name, err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, opts); err != nil {
		return "", fmt.Errorf("scaffold: execute %s: %w", name, err)
	}
	return buf.String(), nil
}

// envStubWithInfra builds the .env body conditional on the picked
// infrastructure. Replaces the older `envStub(name)` for new
// projects; the legacy stub stays for backward compatibility.
func envStubWithInfra(opts ScaffoldOptions) string {
	var b strings.Builder
	fmt.Fprintf(&b, "APP_NAME=%s\nAPP_ENV=local\nAPP_DEBUG=true\nAPP_ADDR=:8080\n\n", opts.Name)
	switch opts.Database {
	case "postgres":
		fmt.Fprintf(&b, "# Postgres (matches docker-compose.yml)\n")
		fmt.Fprintf(&b, "DB_CONNECTION=postgres\nDB_HOST=127.0.0.1\nDB_PORT=5432\n")
		fmt.Fprintf(&b, "DB_USERNAME=app\nDB_PASSWORD=secret\nDB_DATABASE=%s\n", opts.Name)
		fmt.Fprintf(&b, "DB_SSL_MODE=disable\n\n")
	case "mysql":
		fmt.Fprintf(&b, "# MySQL (matches docker-compose.yml)\n")
		fmt.Fprintf(&b, "DB_CONNECTION=mysql\nDB_HOST=127.0.0.1\nDB_PORT=3306\n")
		fmt.Fprintf(&b, "DB_USERNAME=app\nDB_PASSWORD=secret\nDB_DATABASE=%s\n\n", opts.Name)
	case "sqlite":
		fmt.Fprintf(&b, "DB_CONNECTION=sqlite\nDB_DATABASE=app.db\n\n")
	}
	if opts.Cache == "redis" {
		fmt.Fprintf(&b, "# Redis (cache / broadcasting / queue)\nREDIS_ADDR=127.0.0.1:6379\n\n")
	}
	if opts.Storage == "minio" {
		fmt.Fprintf(&b, "# MinIO (S3-compatible)\n")
		fmt.Fprintf(&b, "S3_ENDPOINT=127.0.0.1:9000\nS3_ACCESS_KEY=minioadmin\nS3_SECRET_KEY=minioadmin\n")
		fmt.Fprintf(&b, "S3_BUCKET=%s\nS3_USE_SSL=false\n\n", opts.Name)
	}
	fmt.Fprintf(&b, "JWT_SECRET=please-change-this-to-a-strong-random-secret\n")
	fmt.Fprintf(&b, "# Generated by `lago key:generate`:\nAPP_KEY=\n")
	return b.String()
}
